<?xml version="1.0"?>
<robot xmlns:xacro="http://wiki.ros.org/xacro" name="base_scene" >

  <xacro:arg name="scene" default=""/>

  <!-- Calibration help: If the robot is not moving far enough to the calibration point, increase these distances -->
  <xacro:property name="a_bot_x"	value="0"/>
  <xacro:property name="a_bot_y"	value="-0.4875"/>
  <xacro:property name="b_bot_x"	value="0"/>
  <xacro:property name="b_bot_y"	value="0.4875"/>
  <xacro:property name="b_bot_theta"	value="${pi}"/>
  <xacro:property name="bots_z"		value="0.77"/>

  <!-- This is the main file defining our robot arrangement and physical environment. -->

  <!-- Main workspace -->
  <!-- The surface is 0.01 m below the robot bases and the "workspace_center" frame. -->
  <link name="ground"/>

  <xacro:include filename="$(find o2ac_scene_description
			   )/urdf/components/o2ac_base.xacro" />
  <xacro:include filename="$(find o2ac_scene_description
			   )/urdf/components/o2ac_box.xacro" />
  <xacro:property name="table_w" value="0.9"/>
  <xacro:property name="table_l" value="1.8"/>
  <xacro:property name="table_h" value="0.01"/>
  <xacro:o2ac_box boxname="workbox"
		  box_w="${table_w}" box_l="${table_l}" box_h="${table_h}"
		  parent="ground">
    <origin xyz="${-table_w/2} ${-table_l/2} ${bots_z - table_h}" rpy="0 0 0"/>
  </xacro:o2ac_box>
  <link name="workspace_center"/>
  <joint name="ground_to_workspace" type="fixed">
    <parent link="ground"/>
    <child  link="workspace_center"/>
    <origin xyz="0 0 ${bots_z}" rpy="0 0 0"/>
  </joint>

  <!-- robot arms -->
  <xacro:include filename="$(find ur_description)/urdf/common.gazebo.xacro"/>
  <xacro:include filename="$(find ur_description)/urdf/ur5.urdf.xacro"/>
  <xacro:ur5_robot prefix="a_bot_" joint_limited="false"
    shoulder_pan_lower_limit="${-pi}" shoulder_pan_upper_limit="${pi}"
    shoulder_lift_lower_limit="${-pi}" shoulder_lift_upper_limit="${pi}"
    elbow_joint_lower_limit="0.0" elbow_joint_upper_limit="${pi}"
    wrist_1_lower_limit="${-pi}" wrist_1_upper_limit="${pi}"
    wrist_2_lower_limit="${-pi}" wrist_2_upper_limit="${pi}"
    wrist_3_lower_limit="${-pi}" wrist_3_upper_limit="${pi}"
    kinematics_file="${load_yaml('$(find aist_scene_description
		     )/config/a_bot_calibration.yaml')}"/>

  <xacro:ur5_robot prefix="b_bot_" joint_limited="false"
    shoulder_pan_lower_limit="${-pi}" shoulder_pan_upper_limit="${pi}"
    shoulder_lift_lower_limit="${-pi}" shoulder_lift_upper_limit="${pi}"
    elbow_joint_lower_limit="0.0" elbow_joint_upper_limit="${pi}"
    wrist_1_lower_limit="${-pi}" wrist_1_upper_limit="${pi}"
    wrist_2_lower_limit="${-pi}" wrist_2_upper_limit="${pi}"
    wrist_3_lower_limit="${-pi}" wrist_3_upper_limit="${pi}"
    kinematics_file="${load_yaml('$(find aist_scene_description
		     )/config/b_bot_calibration.yaml')}"/>

  <joint name="ground_a_bot_joint" type="fixed">
    <parent link="ground"/>
    <child  link="a_bot_base_link"/>
    <origin xyz="${a_bot_x} ${a_bot_y} ${bots_z}" rpy="0 0 0"/>
  </joint>

  <joint name="ground_b_bot_joint" type="fixed">
    <parent link="ground"/>
    <child  link="b_bot_base_link"/>
    <origin xyz="${b_bot_x} ${b_bot_y} ${bots_z}" rpy="0 0 ${b_bot_theta}"/>
  </joint>

  <!-- Spawn and attach force sensor -->
  <xacro:include filename="$(find o2ac_scene_description
			   )/urdf/components/ft300.urdf.xacro"/>
  <xacro:ft300 prefix="a_bot_ftsensor_" parent="a_bot_ee_link">
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </xacro:ft300>

  <xacro:ft300 prefix="b_bot_ftsensor_" parent="b_bot_ee_link">
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </xacro:ft300>
>
  <!-- Spawn and attach gripper -->
  <xacro:include filename="$(find o2ac_scene_description
			   )/urdf/components/o2ac_end_effector.urdf.xacro" />
  <xacro:o2ac_end_effector prefix="a_bot_" use_soft_wrist="false"
  			   use_cameras="true"
  			   parent = "a_bot_ftsensor_flange_link" />

  <xacro:include filename="$(find aist_scene_description
  			   )/urdf/components/single_suction_gripper.urdf.xacro"/>
  <xacro:single_suction_gripper prefix="b_bot_gripper_"
  				parent="b_bot_ftsensor_flange_link">
    <origin xyz="0 0 0" rpy="0 ${-0.1*pi/180} ${0.15*pi/180}"/>
  </xacro:single_suction_gripper>

  <!-- Provide force feedback -->
  <gazebo reference="a_bot_wrist_3_joint">
    <provideFeedback>true</provideFeedback>
  </gazebo>
  <gazebo>
    <plugin name="ft_sensor" filename="libgazebo_ros_ft_sensor.so">
      <updateRate>500.0</updateRate>
      <topicName>a_bot/wrench</topicName>
      <gaussianNoise>1.0</gaussianNoise>
      <jointName>a_bot_wrist_3_joint</jointName>
    </plugin>
  </gazebo>

  <gazebo reference="b_bot_wrist_3_joint">
    <provideFeedback>true</provideFeedback>
  </gazebo>
  <gazebo>
    <plugin name="ft_sensor" filename="libgazebo_ros_ft_sensor.so">
      <updateRate>500.0</updateRate>
      <topicName>b_bot/wrench</topicName>
      <gaussianNoise>1.0</gaussianNoise>
      <jointName>b_bot_wrist_3_joint</jointName>
    </plugin>
  </gazebo>

  <!-- I would like to remove the "world" link definition, but apparently it is necessary for Gazebo -->
  <link name="world"/>
  <joint name="world_ground_joint" type="fixed">
    <parent link="world"/>
    <child  link="ground"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <!-- Include indivisual scene file -->
  <xacro:property name="scene_name" value="$(arg scene)"/>
  <xacro:if value="${scene_name != ''}">
    <xacro:include filename="$(find aist_scene_description
			     )/urdf/$(arg scene).urdf.xacro"/>
  </xacro:if>

</robot>
