robot_name: b_bot
waypoints:
- pose: [-0.15, 0, 0.0, -90, 0, 0] # translation, orientation (degrees)
  pose_type: task-space-in-frame
  frame_id: right_centering_link
  speed: 1.0
  desc: Above tray edge
- pose: [-0.07, 0, 0.0, -135, 0, 0] 
  pose_type: task-space-in-frame
  frame_id: right_centering_link
  speed: 1.0
  is_trajectory: True
  blend: 0.01
  desc: Above centering point
- pose: [-0.02, 0, 0.0, -135, 0, 0] 
  pose_type: task-space-in-frame
  frame_id: right_centering_link
  speed: 0.2
  is_trajectory: True
  blend: 0.0
  desc: dropping 
- pose_type: gripper
  gripper:
    action: 'open'
    open_width: 0.085
    velocity: 0.1
- pose_type: gripper
  gripper:
    action: 'close-open'
    open_width: 0.085
    velocity: 0.01
    force: 0
  desc: Centering
- pose: [-0.02, 0, 0.0, -45, 0, 0] 
  pose_type: task-space-in-frame
  frame_id: right_centering_link
  speed: 1.0
- pose_type: gripper
  gripper:
    action: 'close-open'
    open_width: 0.085
    velocity: 0.05
  desc: Centering 
- pose: [-0.02, 0, 0.0, -135, 0, 0] 
  pose_type: task-space-in-frame
  frame_id: right_centering_link
  speed: 1.0
- pose: [0.0, 0, 0.005, 0, -35, 0] 
  pose_type: relative-tcp
  speed: 0.8
- pose_type: gripper
  gripper:
    action: 'close'
    velocity: 0.05
- pose: [0.0, 0, 0.05, 0, 0, 0] 
  pose_type: relative-world
  speed: 0.3
  desc: move up
