robot_name: a_bot
waypoints:
- desc: above_nut_aid
  pose: [1.7012, -1.9212, 1.788, -1.4422, -1.5809, 3.2784]
  pose_type: joint-space
  speed: 1.0
- desc: at_nut_aid
  pose: [0.0, -0.01, -0.25, 0, 0, 0]
  pose_type: relative-base
  speed: 1.0
- pose_type: gripper
  gripper:
    action: open
    velocity: 1.0
- pose: [0.0, 0, 0.25, 0, 0, 0]
  pose_type: relative-base
  speed: 1.0
- pose: 'home'
  pose_type: named-pose
  speed: 1.0
