camera_type: DepthCamera
camera_name: a_bot_outside_camera
robot_name: a_bot
eye_on_hand: true
robot_base_frame: workspace_center
robot_effector_frame: a_bot_ee_link
camera_frame: calibrated_a_bot_outside_camera_color_optical_frame
marker_id: 32
marker_size: 0.07
planarity_tolerance: 0.003
initpose: [0.00, -0.15, 0.35, -90, 90, 0]
keyposes:
  - [-0.25, -0.15, 0.35, -90,  60,  0]
  - [-0.10, -0.15, 0.35, -90,  70,  0]
  - [ 0.00, -0.15, 0.35, -90,  90,  0]
  - [ 0.10, -0.15, 0.35, -90, 110,  0]
  - [ 0.25, -0.15, 0.35, -90, 120,  0]
  - [ 0.00, -0.30, 0.35,   0,  70, 90]
  - [ 0.00, -0.25, 0.35,   0,  80, 90]
  - [ 0.00, -0.05, 0.35,   0, 100, 90]
  - [ 0.00,  0.05, 0.35,   0, 120, 90]
