<?xml version="1.0"?>

<!--
This file is based on the d435 urdf from the realsense package.
The origin of the mesh is at the center of the back mount.
-->

<robot name="sensor_sr305" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:macro name="sensor_sr305" params="prefix parent use_bottom_mount:=false *origin">
    <!-- TODO: Allow placing the camera using bottom mount or back mount -->
    <xacro:property name="M_PI" value="3.1415926535897931" />
  
    <!-- The following values are approximate -->
    <xacro:property name="sr305_cam_depth_to_left_ir_offset" value="0.0"/>
    <xacro:property name="sr305_cam_depth_to_right_ir_offset" value="0.040"/>
    <xacro:property name="sr305_cam_depth_to_color_offset" value="0.015"/>
  
    <!-- The following values model the aluminum case of the
  	sr305 camera, with the camera joint represented by the actual 
  	peripherial camera tripod mount -->
    <xacro:property name="sr305_cam_width" value="0.140"/>
    <xacro:property name="sr305_cam_height" value="0.023"/>
    <xacro:property name="sr305_cam_depth" value="0.012"/>
    <!-- <xacro:property name="sr305_cam_mount_from_center_offset" value="0.0149"/> -->
    <xacro:property name="sr305_cam_mount_from_center_offset" value="0.004"/>

    <!-- Left sensor (looking from front):  -7.54 mm, 0, -3.721 mm -->
    <!-- Right sensor (RGB?)(looking from front): 16.492 mm, 0, -3.721 mm -->
    <!-- 24.033 mm distance between the camera centers, apparently -->
    <!-- camera mount to origin: 4mm; cameras to origin: 3.721 mm. = 7.721 mm offset? -->
  
    <!-- The following offset is relative to the physical sr305 camera peripheral
  	camera tripod mount -->
    <xacro:property name="sr305_cam_depth_px" value="${sr305_cam_mount_from_center_offset}"/>
    <xacro:property name="sr305_cam_depth_py" value="0.0"/>
    <xacro:property name="sr305_cam_depth_pz" value=".013063"/>

    
    <!-- camera body, with origin at bottom screw mount -->
    <xacro:if value="${use_bottom_mount}">
      <joint name="${prefix}camera_joint" type="fixed">
        <xacro:insert_block name="origin" />
        <parent link="${parent}"/>
        <child link="${prefix}camera_bottom_screw_frame" />
      </joint>
      <link name="${prefix}camera_bottom_screw_frame"/>

      <joint name="${prefix}camera_link_joint" type="fixed">
        <origin xyz="${sr305_cam_depth_px} ${sr305_cam_depth_py} ${sr305_cam_depth_pz}" rpy="0 0 0"/>
        <parent link="${prefix}camera_bottom_screw_frame"/>
        <child link="${prefix}camera_link" />
      </joint>
    </xacro:if>

    <xacro:if value="${not use_bottom_mount}">
      <!-- I forgot which conventions exist for "camera_joint" and "camera_link_joint" so I hesitate to delete one. -->
      <joint name="${prefix}camera_joint" type="fixed">
        <xacro:insert_block name="origin" />
        <parent link="${parent}"/>
        <child link="${prefix}camera_connector_link" />
      </joint>
      <link name="${prefix}camera_connector_link"/>

      <joint name="${prefix}camera_link_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <parent link="${prefix}camera_connector_link"/>
        <child link="${prefix}camera_link" />
      </joint>
    </xacro:if>

    <link name="${prefix}camera_link">
      <visual>
      <origin xyz="${0} ${-sr305_cam_depth_py} 0" rpy="${M_PI/2} 0 ${M_PI/2}"/>
        <geometry>
          <xacro:if value="${use_bottom_mount}">
	          <mesh filename="package://o2ac_scene_description/meshes/sr305_simplified.stl" scale=".001 .001 .001" />
          </xacro:if>
          <xacro:if value="${not use_bottom_mount}">
	          <mesh filename="package://o2ac_scene_description/meshes/sr305_simplified_body.stl" scale=".001 .001 .001" />
          </xacro:if>
        </geometry>
        <material name="sr305_aluminum">
          <color rgba="0.5 0.5 0.5 1"/>
        </material>
      </visual>
      <collision>
        <origin xyz="${sr305_cam_depth/2} ${-sr305_cam_depth_py} 0" rpy="0 0 0"/>
        <geometry>
          <box size="${sr305_cam_depth} ${sr305_cam_width} ${sr305_cam_height}"/>
        </geometry>
      </collision>
      <inertial>
        <!-- The following are not reliable values, and should not be used for modeling -->
        <mass value="0.564" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.003881243" ixy="0.0" ixz="0.0" iyy="0.000498940" iyz="0.0" izz="0.003879257" />
      </inertial>
    </link>
   
    <!-- camera depth joints and links -->
    <joint name="${prefix}camera_depth_joint" type="fixed">
      <origin xyz=".003721 0 0" rpy="0 0 0"/>
      <parent link="${prefix}camera_link"/>
      <child link="${prefix}camera_depth_frame" />
    </joint>
    <link name="${prefix}camera_depth_frame"/>

    <joint name="${prefix}camera_depth_optical_joint" type="fixed">
      <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
      <parent link="${prefix}camera_depth_frame" />
      <child link="${prefix}camera_depth_optical_frame" />
    </joint>
    <link name="${prefix}camera_depth_optical_frame"/>
      
    <!-- camera left IR joints and links -->
    <joint name="${prefix}camera_left_ir_joint" type="fixed">
      <origin xyz="0 ${sr305_cam_depth_to_left_ir_offset} 0" rpy="0 0 0" />
      <parent link="${prefix}camera_depth_frame" />
      <child link="${prefix}camera_left_ir_frame" />
    </joint>
    <link name="${prefix}camera_left_ir_frame"/>

    <joint name="${prefix}camera_left_ir_optical_joint" type="fixed">
      <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
      <parent link="${prefix}camera_left_ir_frame" />
      <child link="${prefix}camera_left_ir_optical_frame" />
    </joint>
    <link name="${prefix}camera_left_ir_optical_frame"/>

    <!-- camera right IR joints and links -->
    <joint name="${prefix}camera_right_ir_joint" type="fixed">
      <origin xyz="0 ${sr305_cam_depth_to_right_ir_offset} 0" rpy="0 0 0" />
      <parent link="${prefix}camera_depth_frame" />
      <child link="${prefix}camera_right_ir_frame" />
    </joint>
    <link name="${prefix}camera_right_ir_frame"/>

    <joint name="${prefix}camera_right_ir_optical_joint" type="fixed">
      <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
      <parent link="${prefix}camera_right_ir_frame" />
      <child link="${prefix}camera_right_ir_optical_frame" />
    </joint>
    <link name="${prefix}camera_right_ir_optical_frame"/>

    <!-- camera color joints and links -->
    <joint name="${prefix}camera_color_joint" type="fixed">
      <origin xyz="0 ${sr305_cam_depth_to_color_offset} 0" rpy="0 0 0" />
      <parent link="${prefix}camera_depth_frame" />
      <child link="${prefix}camera_color_frame" />
    </joint>
    <link name="${prefix}camera_color_frame"/>

    <joint name="${prefix}camera_color_optical_joint" type="fixed">
      <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
      <parent link="${prefix}camera_color_frame" />
      <child link="${prefix}camera_color_optical_frame" />
    </joint>
    <link name="${prefix}camera_color_optical_frame"/>

    <gazebo reference="${prefix}camera_depth_frame">
      <sensor type="depth" name="${prefix}camera">
	<always_on>true</always_on>
	<visualize>true</visualize>
	<camera>
          <horizontal_fov>1.034</horizontal_fov>
          <image>
            <width>640</width>
            <height>480</height>
            <format>R8G8B8</format>
          </image>
          <depth_camera>
          </depth_camera>
          <clip>
            <near>0.1</near>
            <far>100</far>
          </clip>
	</camera>
	<plugin name="${prefix}cam_controller"
		filename="libgazebo_ros_openni_kinect.so">
          <baseline>0.2</baseline>
          <alwaysOn>true</alwaysOn>
          <updateRate>10.0</updateRate>
          <cameraName>${prefix}camera</cameraName>
          <frameName>${prefix}camera_color_optical_frame</frameName>
          <imageTopicName>color/image_raw</imageTopicName>
          <cameraInfoTopicName>color/camera_info</cameraInfoTopicName>
          <depthImageTopicName>aligned_depth_to_color/image_raw</depthImageTopicName>
          <depthImageCameraInfoTopicName>aligned_depth_to_color/camera_info</depthImageCameraInfoTopicName>
          <pointCloudTopicName>depth/points</pointCloudTopicName>
          <pointCloudCutoff>0.1</pointCloudCutoff>
          <!-- <hackBaseline>0.07</hackBaseline> -->
          <distortionK1>0.0</distortionK1>
          <distortionK2>0.0</distortionK2>
          <distortionK3>0.0</distortionK3>
          <distortionT1>0.0</distortionT1>
          <distortionT2>0.0</distortionT2>
          <CxPrime>0.0</CxPrime>
          <Cx>0.0</Cx>
          <Cy>0.0</Cy>
          <focalLength>0.0</focalLength>
	</plugin>
      </sensor>
    </gazebo>

  </xacro:macro>
</robot>
