camera_type: DepthCamera
camera_name: a_bot_outside_camera
robot_name: a_bot
eye_on_hand: true
robot_base_frame: workspace_center
robot_effector_frame: a_bot_ee_link
camera_frame: calibrated_a_bot_outside_camera_color_optical_frame
marker_id: 26
marker_size: 0.083
planarity_tolerance: 0.003
initpose: [-0.14, -0.15, 0.38, -90, 90, 0]
keyposes:
  - [-0.34, -0.15, 0.35, -90,  60,  0]
  - [-0.24, -0.15, 0.35, -90,  70,  0]
  - [-0.14, -0.15, 0.35, -90,  90,  0]
  - [-0.04, -0.15, 0.35, -90, 110,  0]
  - [ 0.05, -0.15, 0.35, -90, 120,  0]
  - [-0.14, -0.25, 0.35,   0,  70, 90]
  - [-0.14, -0.20, 0.35,   0,  80, 90]
  - [-0.14, -0.10, 0.35,   0, 100, 90]
  - [-0.14, -0.05, 0.35,   0, 110, 90]
