<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"
       name="o2ac_base_scene" >

  <xacro:property name="b_bot_x" value="0.003"/>
  <xacro:property name="b_bot_y" value="0.525"/>
  <xacro:property name="b_bot_z" value="0.0"/>
  <xacro:property name="b_bot_z_angle" value="${-3.1415926}"/> <!-- Mirror a_bot + calibration offset -->
  <xacro:property name="b_bot_y_angle" value="0"/>

  <xacro:property name="bots_z" value="0.75"/>

  <xacro:include filename="$(find o2ac_scene_description)/urdf/ur_gazebo.xacro"/> 
  <gazebo>
    <plugin name="ros_control" filename="libgazebo_ros_control.so">
    </plugin>
  </gazebo>
  
  <!-- <xacro:include filename="$(find o2ac_gazebo)/urdf/o2ac_base_scene.gazebo" /> -->

  <!-- robots -->

  <xacro:include filename="$(find o2ac_scene_description)/urdf/cooking_environment.xacro" />
  
  
  <!-- Robot bases -->
  <!-- Putting these at height 0.0 makes them intersect with the ground, so they are elevated. -->
  <!-- There are some instabilities in Gazebo when the box is big, for some reason. -->
  <xacro:include filename="$(find o2ac_scene_description)/urdf/components/o2ac_base.xacro" />
  <xacro:o2ac_base boxname="b_bot_base_smfl" parent="o2ac_ground">
    <origin xyz="${b_bot_x-.65/2} ${b_bot_y-.65/2} ${bots_z-.05}" rpy="0 0 0" />
  </xacro:o2ac_base>

  <!-- Main workspace -->
  <xacro:include filename="$(find o2ac_scene_description)/urdf/components/o2ac_box.xacro" />
  <xacro:property name="workplate_w" value="0.65"/>
  <xacro:property name="workplate_l" value="0.4"/>
  <xacro:property name="workplate_h" value="0.02"/>
  <xacro:property name="robot_mount_plate" value="-0.003"/>  <!-- The plate holding the robots, resting on the alu frames -->
  <xacro:o2ac_box boxname="workplate" box_w="${workplate_w}" box_l="${workplate_l}" box_h="${workplate_h}" parent="o2ac_ground">
    <origin xyz="${-workplate_w/2} ${-(workplate_l/2)} ${bots_z-robot_mount_plate}" rpy="0 0 0" />
  </xacro:o2ac_box>
  <link name="workspace_center" />
  <joint name="world_to_workspace" type="fixed">
    <parent link="o2ac_ground" />
    <child link="workspace_center" />
    <origin xyz="0.0 0.0 ${bots_z-robot_mount_plate+workplate_h}" rpy="0.0 0.0 0.0" />
  </joint>

  <xacro:ur_robot
    prefix="b_bot_"
    joint_limits_parameters_file='$(find o2ac_scene_description)/config/b_bot_joint_limits.yaml'
    kinematics_parameters_file='$(find o2ac_scene_description)/config/b_bot_calibration.yaml'
    physical_parameters_file='$(find ur_description)/config/ur5e/physical_parameters.yaml'
    visual_parameters_file='$(find ur_description)/config/ur5e/visual_parameters.yaml'
    transmission_hw_interface='hardware_interface/PositionJointInterface'
    safety_limits="false"
    safety_pos_margin="0.15"
    safety_k_position="20"
  />
  
  <link name="b_bot_ee_link">
    <collision>
      <geometry>
        <box size="0.01 0.01 0.01"/>
      </geometry>
      <origin rpy="0 0 0" xyz="-0.01 0 0"/>
    </collision>
  </link>
  <joint name="b_bot_ee_fixed_joint" type="fixed">
    <parent link="b_bot_wrist_3_link"/>
    <child link="b_bot_ee_link"/>
    <origin rpy="0.0 -1.57079632679 1.57079632679" xyz="0.0 0.0 0.0"/>
  </joint>

  <link name="o2ac_ground" />

  <link name="b_bot_intermediate_link" />
  <joint name="world_b_bot_intermediate_joint" type="fixed">
    <parent link="o2ac_ground" />
    <child link="b_bot_intermediate_link" />
    <origin xyz="${b_bot_x} ${b_bot_y} ${bots_z+b_bot_z}" rpy="0.0 0.0 ${b_bot_z_angle}" />
  </joint>

  <joint name="world_b_bot_joint" type="fixed">
    <parent link="b_bot_intermediate_link" />
    <child link="b_bot_base_link" />
    <origin xyz="0 0 0" rpy="${-b_bot_y_angle} 0.0 0.0" />
  </joint>

  <!-- Load knife already grasped -->
  <xacro:include filename="$(find o2ac_scene_description)/urdf/components/o2ac_knife.urdf.xacro" />

  <xacro:o2ac_end_effector prefix="b_bot_" use_soft_wrist="false" use_cameras="true" parent = "b_bot_ee_link" />

  <gazebo reference="b_bot_wrist_3_joint">
  <provideFeedback>true</provideFeedback>
  </gazebo>
  <gazebo>
    <plugin name="ft_sensor" filename="libgazebo_ros_ft_sensor.so">
      <updateRate>500.0</updateRate>
      <topicName>b_bot/wrench</topicName>
      <gaussianNoise>0.0</gaussianNoise>
      <jointName>b_bot_wrist_3_joint</jointName>
    </plugin>
  </gazebo>

  <!-- The "world" link definition should be removed, but apparently it is necessary for Gazebo -->
  <link name="world" />
  <joint name="world_o2ac_joint" type="fixed">
    <parent link="world" />
    <child link="o2ac_ground" />
    <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
  </joint>

</robot>
