<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"
  name="o2ac_environment">

  <xacro:include filename="$(find o2ac_scene_description)/urdf/components/o2ac_box.xacro" />
  <xacro:include filename="$(find o2ac_scene_description)/urdf/components/o2ac_box_2.xacro" />
  <!-- This file defines the frames surrounding the robots, used to fix the tools, multi-jig etc. -->
  <xacro:property name="vert_column_x_back" value="${-.325-.15-.04}" />

  <xacro:o2ac_box boxname="vertical_column_right" box_w=".04" box_l=".04" box_h="2.0" parent="o2ac_ground">
    <origin xyz="${vert_column_x_back} .2 0" rpy="0 0 0" />
  </xacro:o2ac_box>
  <xacro:o2ac_box boxname="vertical_column_left" box_w=".04" box_l=".04" box_h="2.0" parent="o2ac_ground">
    <origin xyz="${vert_column_x_back} -.24 0" rpy="0 0 0" />
  </xacro:o2ac_box>

  <xacro:o2ac_box boxname="horizontal_column_top" box_w=".04" box_l=".4" box_h=".04" parent="o2ac_ground">
    <origin xyz="${vert_column_x_back} -.2 1.96" rpy="0 0 0" />
  </xacro:o2ac_box>

  <xacro:o2ac_box boxname="horizontal_column_for_tools" box_w=".04" box_l=".4" box_h=".04" parent="o2ac_ground">
    <origin xyz="${vert_column_x_back} -.2 1.058" rpy="0 0 0" />
  </xacro:o2ac_box>

  <!-- Invisible walls to avoid OMPL creating crazy plans (sanity limits) -->
  <xacro:o2ac_box_2 boxname="agv_table" box_w=".6" box_l=".5" box_h=".05" invisible="true" parent="workspace_center">
    <origin xyz=".65 0 -.04" rpy="0 0 0" />
  </xacro:o2ac_box_2>

  <xacro:o2ac_box_2 boxname="back_limit_a" box_w=".05" box_l=".5" box_h=".5" invisible="true" parent="workspace_center">
    <origin xyz="${vert_column_x_back} -.5 .3" rpy="0 0 0" />
  </xacro:o2ac_box_2>

  <xacro:o2ac_box_2 boxname="back_limit_b" box_w=".05" box_l=".5" box_h=".5" invisible="true" parent="workspace_center">
    <origin xyz="${vert_column_x_back} .5 .3" rpy="0 0 0" />
  </xacro:o2ac_box_2>

  <xacro:o2ac_box_2 boxname="side_limit_a" box_w="1.0" box_l=".05" box_h="1.0" invisible="true" parent="workspace_center">
    <origin xyz=".0 1.1 .5" rpy="0 0 0" />
  </xacro:o2ac_box_2>
  <xacro:o2ac_box_2 boxname="side_limit_b" box_w="1.0" box_l=".05" box_h="1.0" invisible="true" parent="workspace_center">
    <origin xyz=".0 -1.1 .5" rpy="0 0 0" />
  </xacro:o2ac_box_2>

  <!-- Screw holder & screw tool visual -->
  <xacro:include filename="$(find o2ac_scene_description)/urdf/components/cookingtools.xacro" />

  <link name="tray_center" />
  <joint name="tray_center_joint" type="fixed">
    <parent link="workspace_center" />
    <child link="tray_center" />
    <origin rpy="0 0 0" xyz="0.14 0 0.005" />
  </joint>

  <!-- Base fixture -->
  <xacro:include filename="$(find o2ac_scene_description)/urdf/components/base_fixture.xacro" />
  <xacro:base_fixture parent="workspace_center">
    <origin xyz="-0.294 -.18 0" rpy="0 0 0" />
  </xacro:base_fixture>

  <joint name="right_storage_area_joint" type="fixed">
    <parent link="workspace_center" />
    <child link="right_storage_area_link" />
    <origin xyz="0.25 0.50 -0.0149" rpy="0 ${pi/2} -${pi/2}" />
  </joint>
  <link name="right_storage_area_link" />

  <joint name="right_centering_joint" type="fixed">
    <parent link="workspace_center" />
    <child link="right_centering_link" />
    <origin xyz="0.20 0.30 -0.0149" rpy="0 ${pi/2} -${pi/2}" />
  </joint>
  <link name="right_centering_link" />

  <joint name="left_centering_joint" type="fixed">
    <parent link="workspace_center" />
    <child link="left_centering_link" />
    <origin xyz="0.20 -0.30 -0.0149" rpy="0 ${pi/2} -${pi/2}" />
  </joint>
  <link name="left_centering_link" />

  <!-- ======== -->
  <!-- TV -->

  <link name="tv">
    <!-- This tv box origin is at the front bottom, so it can more easily be measured  -->
    <xacro:property name="tv_length_x" value="0.06" />
    <xacro:property name="tv_length_y" value="0.96" />
    <xacro:property name="tv_length_z" value="0.56" />

    <visual>
      <origin xyz="${-tv_length_x/2} 0.0 ${tv_length_z/2}" rpy="0 0 0" />
      <geometry>
        <box size="${tv_length_x} ${tv_length_y} ${tv_length_z}" />
      </geometry>
      <material name="Black">
        <color rgba="0.1 0.1 0.1 1.0" />
      </material>
    </visual>
    <collision>
      <origin xyz="${-tv_length_x/2} 0.0 ${tv_length_z/2}" rpy="0 0 0" />
      <geometry>
        <!-- 7.5 cm on each side -->
        <box size="${tv_length_x + 0.15} ${tv_length_y + 0.15} ${tv_length_z+0.1}" />
      </geometry>
    </collision>
    <!-- This is required for Gazebo. -->
    <inertial>
      <mass value="1.0" />
      <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0" />
    </inertial>
  </link>
  <gazebo reference="tv">
    <material>Gazebo/Black</material>
  </gazebo>
  <joint name="tv_joint" type="fixed">
    <parent link="o2ac_ground" />
    <child link="tv" />
    <origin xyz="-0.4 0.0 1.58" rpy="0 0 0" />
  </joint>

  <!-- Cooking environments -->

  <!-- cutting board box stl-->
  <link name="cutting_board">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0.008" />
      <geometry>
        <mesh filename="package://o2ac_scene_description/meshes/cutting_board.stl" scale="0.85 1.4 1" />
      </geometry>
      <material name="blue">
        <color rgba=".0 .4 .8 1" />
      </material>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0.008" />
      <geometry>
        <mesh filename="package://o2ac_scene_description/meshes/cutting_board.stl" scale="0.85 1.4 1" />
      </geometry>
    </collision>
  </link>
  <joint name="cutting_board_joint" type="fixed">
    <parent link="workspace_center" />
    <child link="cutting_board" />
    <origin rpy="0 0 0" xyz="-0.135 0.02 0.085" />
  </joint>
  <gazebo reference="cutting_board">
    <material>Gazebo/Blue</material>
  </gazebo>

  <link name="cutting_board_surface" />
  <joint name="cutting_board_surface" type="fixed">
    <parent link="cutting_board" />
    <child link="cutting_board_surface" />
    <origin rpy="0 0 0" xyz="0 0 0.018" />
  </joint>

  <link name="cutting_board_disect_inter" />
  <joint name="cutting_board_disect_inter" type="fixed">
    <parent link="cutting_board" />
    <child link="cutting_board_disect_inter" />
    <origin rpy="${pi/2} 0 0" xyz="0 0 0.018" />
  </joint>

  <link name="cutting_board_disect" />
  <joint name="cutting_board_disect" type="fixed">
    <parent link="cutting_board_disect_inter" />
    <child link="cutting_board_disect" />
    <origin rpy="0 ${-pi/2} 0" xyz="0 0 0" />
  </joint>

  <link name="knife_holder">
    <visual>
      <origin rpy="0 0 ${pi/2}" xyz="0 0 0" />
      <geometry>
        <mesh filename="package://o2ac_scene_description/meshes/knife_holder.stl" scale="1 1 1" />
      </geometry>
      <material name="blue">
        <color rgba=".0 .4 .8 1" />
      </material>
    </visual>
    <collision>
      <origin rpy="0 0 ${pi/2}" xyz="0 0 0" />
      <geometry>
        <mesh filename="package://o2ac_scene_description/meshes/knife_holder.stl" scale="1 1 1" />
      </geometry>
    </collision>
  </link>
  <joint name="knife_holder_joint" type="fixed">
    <parent link="workspace_center" />
    <child link="knife_holder" />
    <origin rpy="0 0 ${-pi/2}" xyz="-0.30 0.35 -0.015" />
  </joint>
  <gazebo reference="knife_holder">
    <material>Gazebo/Blue</material>
  </gazebo>

</robot>
