dt: 0.002 # 500Hz
position:
  p: [1.5, 1.5, 1.5, 1., 1., 1.]
  d: 'default'
  i: 'default'
  dynamic: True # Caution: makes the p-gain variable
force:
  p: [0.01, 0.01, 0.01, 1.0, 1.0, 1.0]
  d: 'default'
  i: 'default'
  dynamic: False
force_position_selection_matrix: [1., 1., 1., 1., 1., 1.] # 1: position control, 0: force control, any value in between is a compromise of position and force
max_force_torque: [30., 30., 30., 4., 4., 4.] # try to avoid emergency stops with a lower max force torque 
