# This is the b_bot specific controller file defining the prefixed joints

# Settings for ros_control control loop
hardware_control_loop:
   loop_hz: 500

# Settings for ros_control hardware interface
ur_hardware_interface:
   joints: &robot_joints
     - b_bot_shoulder_pan_joint
     - b_bot_shoulder_lift_joint
     - b_bot_elbow_joint
     - b_bot_wrist_1_joint
     - b_bot_wrist_2_joint
     - b_bot_wrist_3_joint

# Publish all joint states ----------------------------------
joint_state_controller:
   type:         joint_state_controller/JointStateController
   publish_rate: 500

# Publish wrench ----------------------------------
force_torque_sensor_controller:
   type:         force_torque_sensor_controller/ForceTorqueSensorController
   publish_rate: 500

# Publish speed_scaling factor
speed_scaling_state_controller:
   type:         scaled_controllers/SpeedScalingStateController
   publish_rate: 500

# Joint Trajectory Controller - position based -------------------------------
# For detailed explanations of parameter see http://wiki.ros.org/joint_trajectory_controller
scaled_pos_joint_traj_controller:
   type: position_controllers/ScaledJointTrajectoryController
   joints: *robot_joints
   constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      b_bot_shoulder_pan_joint: {trajectory: 0.2, goal: 0.1}
      b_bot_shoulder_lift_joint: {trajectory: 0.2, goal: 0.1}
      b_bot_elbow_joint: {trajectory: 0.2, goal: 0.1}
      b_bot_wrist_1_joint: {trajectory: 0.2, goal: 0.1}
      b_bot_wrist_2_joint: {trajectory: 0.2, goal: 0.1}
      b_bot_wrist_3_joint: {trajectory: 0.2, goal: 0.1}
   stop_trajectory_duration: 0.5
   state_publish_rate: 500
   action_monitor_rate: 10

pos_joint_traj_controller:
   type: position_controllers/JointTrajectoryController
   joints: *robot_joints
   constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      b_bot_shoulder_pan_joint: {trajectory: 0.2, goal: 0.1}
      b_bot_shoulder_lift_joint: {trajectory: 0.2, goal: 0.1}
      b_bot_elbow_joint: {trajectory: 0.2, goal: 0.1}
      b_bot_wrist_1_joint: {trajectory: 0.2, goal: 0.1}
      b_bot_wrist_2_joint: {trajectory: 0.2, goal: 0.1}
      b_bot_wrist_3_joint: {trajectory: 0.2, goal: 0.1}
   stop_trajectory_duration: 0.5
   state_publish_rate: 500
   action_monitor_rate: 10

cartesian_compliance_controller:
   type: "position_controllers/CartesianComplianceController"
   end_effector_link: "b_bot_gripper_tip_link"
   robot_base_link: "b_bot_base_link"
   ft_sensor_ref_link: "b_bot_wrist_3_link"
   compliance_ref_link: "b_bot_gripper_tip_link"
   target_frame_topic: "target_frame"
   joints:
   - b_bot_shoulder_pan_joint
   - b_bot_shoulder_lift_joint
   - b_bot_elbow_joint
   - b_bot_wrist_1_joint
   - b_bot_wrist_2_joint
   - b_bot_wrist_3_joint

   stiffness: # w.r.t. compliance_ref_link
     trans_x: 500
     trans_y: 500
     trans_z: 500
     rot_x: 20
     rot_y: 20
     rot_z: 20
   
     use_parallel_force_position_control: True
   
     ### Selection matrix parameters ###
     # 0 means force control only
     # 1 means position control only
     # values in between are a trade-off of both controllers
     sel_x: 1.0 
     sel_y: 1.0
     sel_z: 1.0 
     sel_ax: 1.0
     sel_ay: 1.0
     sel_az: 1.0

   solver:
      error_scale: 0.3
      # iterations: 1

   pd_gains:
      trans_x: {p: 0.05}
      trans_y: {p: 0.05}
      trans_z: {p: 0.05}
      rot_x: {p: 1.0}
      rot_y: {p: 1.0}
      rot_z: {p: 1.0}

   gravity:
      x: 0
      y: 0
      z: 0

   tool:
      # Mass of everything that's mounted after the sensor.
      mass: 1.250

      # The center of mass in the ft_sensor_ref_link.
      # Take a measure and try to estimate that as good as possible.
      com_x: 0.001
      com_y: -0.016
      com_z: 0.050
